import itertools
import argparse

from torchvision.utils import save_image
import os
import sys
import torchvision.transforms as transforms
from torch.utils.data import DataLoader
from torch.autograd import Variable
from PIL import Image
import torch
import torchvision
import numpy as np

from models import Generator
from models import Discriminator
from utils import ReplayBuffer
from utils import weights_init_normal

# parameters
parser = argparse.ArgumentParser()
parser.add_argument('--epochs', type=int, default=200, help='number of epochs of training')
parser.add_argument('--batch_size', type=int, default=1, help='size of the batches')
parser.add_argument('--output_imgs', type=int, default=10, help='how many images to generated by cycle gan')
parser.add_argument('--old_root', type=str, default='old/', help='root directory of the dataset')
parser.add_argument('--young_root', type=str, default='young/', help='root directory of the dataset')
parser.add_argument('--lr', type=float, default=0.0002, help='initial learning rate')
parser.add_argument('--decay_epoch', type=int, default=100, help='epoch to start linearly decaying the learning rate to 0')
parser.add_argument('--img_size', type=int, default=32, help='size of the data crop (squared assumed)')
parser.add_argument('--input_nc', type=int, default=3, help='number of channels of input data')
parser.add_argument('--output_nc', type=int, default=3, help='number of channels of output data')
parser.add_argument('--cuda', action='store_true', help='use GPU computation')
parser.add_argument('--n_cpu', type=int, default=8, help='number of cpu threads to use during batch generation')
opt = parser.parse_args()

print(opt)
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

###### Definition of variables ######
# Networks
netG_A2B = Generator(opt.input_nc, opt.output_nc)
netG_B2A = Generator(opt.output_nc, opt.input_nc)

# Load state dicts
netG_A2B.load_state_dict(torch.load('ckpt/netG_A2B.pth'))
netG_B2A.load_state_dict(torch.load('ckpt/netG_B2A.pth'))

netG_A2B.to(device)
netG_B2A.to(device)

# Set model's test mode
netG_A2B.eval()
netG_B2A.eval()

# Dataset loader
transform = transforms.Compose([transforms.Resize((opt.img_size, opt.img_size)), transforms.ToTensor(), transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))])
old_set = torchvision.datasets.ImageFolder(opt.old_root, transform)
young_set = torchvision.datasets.ImageFolder(opt.young_root, transform)
old_loader = torch.utils.data.DataLoader(dataset=old_set,batch_size=opt.batch_size,shuffle=True)
young_loader = torch.utils.data.DataLoader(dataset=young_set,batch_size=opt.batch_size,shuffle=True)

# Result output directory
if not os.path.exists('output/old'):
    os.makedirs('output/old')
if not os.path.exists('output/young'):
    os.makedirs('output/young')

# Inputs & targets memory allocation
Tensor = torch.cuda.FloatTensor if torch.cuda.is_available() else torch.Tensor
input_A = Tensor(opt.batch_size, opt.input_nc, opt.img_size, opt.img_size)
input_B = Tensor(opt.batch_size, opt.output_nc, opt.img_size, opt.img_size)
target_real = Variable(Tensor(opt.batch_size).fill_(1.0), requires_grad=False)
target_fake = Variable(Tensor(opt.batch_size).fill_(0.0), requires_grad=False)

i = 0 # generate image iteration count
for batch in zip(old_loader, young_loader):
    # Set model input
    A = torch.FloatTensor(batch[0][0])
    B = torch.FloatTensor(batch[1][0])
    real_A = Variable(input_A.copy_(A))
    real_B = Variable(input_B.copy_(B))

    # Generate output
    fake_B = 0.5*(netG_A2B(real_A).data + 1.0)
    fake_A = 0.5*(netG_B2A(real_B).data + 1.0)

    # Save image files
    save_image(real_A / 2 + 0.5, 'output/old/real%04d.png' % (i+1))
    save_image(real_B / 2 + 0.5, 'output/young/real%04d.png' % (i+1))
    save_image(fake_A, 'output/old/fake%04d.png' % (i+1))
    save_image(fake_B, 'output/young/fake%04d.png' % (i+1))

    print('\rGenerated images %04d' % (i+1))
    i = i + 1
    if i == opt.output_imgs:
        break

print('Finished generating images by CycleGAN')
